baseURL = 'https://timbeaudet.com/blog/'
languageCode = 'en-us'
title = "TimBeaudet::GameDeveloper()"
description = "Game Development"
theme = 'LoveIt'
[[module.mounts]]
	source = "layouts"
	target = "layouts"
[markup.goldmark.renderer]
	unsafe= true

[params]
	# site default theme ["auto", "light", "dark"]
	defaultTheme = "dark"
	dateFormat = "2006-01-02"
	# website title for Open Graph and Twitter Cards
	title = "Tim Beaudet"
	description = "Game Development, Hiking and Ramblings of a Programmer"
	# website images for Open Graph and Twitter Cards
	# images = ["/logo.png"]

[params.author]
	name = "TimBeaudet"
	email = "tim@tyrebytes.com"
	link = "https://www.twitch.tv/timbeaudet"

[params.home]
	rss = 10
	[params.home.profile]
		enable = true
		# LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
		title = "Ramblings of a Programmer"
		# subtitle shown in home page (HTML format is supported)
		subtitle = "This Blog is Under Construction..."
		# whether to use typeit animation for subtitle
		typeit = true
		# whether to show social links
		social = true
		# LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
		disclaimer = ""
	[params.home.posts]
		enable = true
		paginate = 6
		defaultHiddenFromHomePage = false

[menu]
	[[menu.main]]
		weight = 1
		identifier = "posts"
		pre = ""
		post = ""
		name = "Posts"
		url = "/posts/"
		title = ""
	[[menu.main]]
		weight = 2
		identifier = "tags"
		pre = ""
		post = ""
		name = "Tags"
		url = "/tags/"
		title = ""
	[[menu.main]]
		weight = 3
		identifier = "categories"
		pre = ""
		post = ""
		name = "Categories"
		url = "/categories/"
		title = ""

# Header config
[params.header]
	# desktop header mode ["fixed", "normal", "auto"]
	desktopMode = "fixed"
	# mobile header mode ["fixed", "normal", "auto"]
	mobileMode = "auto"
	# LoveIt NEW | 0.2.0 Header title config

[params.header.title]
	# URL of the LOGO
	logo = ""
	# title name
	name = ""
	# you can add extra information before the name (HTML format is supported), such as icons
	pre = ""
	# you can add extra information after the name (HTML format is supported), such as icons
	post = ""
	# LoveIt NEW | 0.2.5 whether to use typeit animation for title name
	typeit = false

# Footer config
[params.footer]
	enable = true
	custom = ''
	hugo = false
	copyright = false
	author = false
	since = 2007
	# ICP info only in China (HTML format is supported)
	icp = ""
	license = ''
