---
- hosts: all
  gather_facts: no

  vars:
    - username: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Creates directory
      file:
        path: timbeaudet/public
        state: directory
    - name: Create symbolic link 
      file:
        #dest is the LINK and src is TARGET
        src: "timbeaudet/public"
        dest: "timbeaudet.com"
        state: link
